language: dart
dart: stable

dart_task:
  - test: --platform vm
  - test: --platform chrome
  - dartanalyzer: --fatal-warnings --fatal-infos .
  - dart_style

after_success:
  - pub global activate dart_coveralls
  - pub global run dart_coveralls report test/all_test.dart
